### ISSUE TITLE
Al ingresar 2 números en la calculadora...

### ISSUE THREAD

**Issue by MARSFOREVER472** [MARSFOREVER472/CalculadoraInterfaz#1]
...no me despliega el resultado, si es que mi compañero organizador me pueda ayudar!

Saludos!

**Comment by Autinfit** [comment]
Estimado:

Si posees este inconveniente, es porque probablemente trabajas en 2 archivos por separado, las cuales redistribuyes en HTML y en JavaScript por carpeta, entonces es posible que no lo estás tomando la función que ingresaste, lo que sugiero es que juntes esos 2 archivos dentro de una misma carpeta para que la función lo pueda reconocer de mejor forma.

Espero te sirva de ayuda!

Saludos!

**Comment by MARSFOREVER472** [comment]
Muchas gracias estimado!!!

Con esto da gusto en ayudarme con este problema!!!

Saludos!!!!
